name: Release Helm

on:
  push:
    tags:
      - helm/v*.*.*
    branches-ignore:
      - '**'

jobs:
  release-helm:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: motoki317
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package chart
        run: |
          cd charts
          helm package test

      - name: Publish chart
        run: |
          cd charts
          helm push test-*.tgz oci://ghcr.io/motoki317/charts
